services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    env_file:
      - /home/ubuntu/docker-env.env
    environment:
      MYSQL_ROOT_PASSWORD: examplepw
      MYSQL_DATABASE: mydb
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 10s

  app:
    image: ggamnunq/umc:backend
    container_name: spring-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb/anonymous_board?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: examplepw
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  nginx:
    image: ggamnunq/umc:nginx
    container_name: my-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  db_data:
