spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URLDD}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: GET, POST, PATCH, DELETE, PUT
      allowed-headers: "*"
      allow-credentials: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

    # 잠시 보류
#cloud:
#  aws:
#    s3:
#      bucket: umc-7th
#      path:
#        photo: photos
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY_ID}
#      secretKey: ${AWS_SECRET_ACCESS_KEY}