spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: umc_user
    password: umc_password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true

  web:
    cors:
      allowed-origins: "http://localhost:5173"

cloud:
  aws:
    credentials:
      accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      secretKey: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
      path:
        photo: ${CLOUD_AWS_S3_PATH_PHOTO}
