spring:
#  config:
#    import: "classpath:.env"  # .env 파일을 로드

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/mydb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: GET, POST, PATCH, DELETE, PUT
      allowed-headers: "*"
      allow-credentials: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080
  address: 0.0.0.0

    # 잠시 보류
#cloud:
#  aws:
#    s3:
#      bucket: umc-7th
#      path:
#        photo: photos
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY_ID}
#      secretKey: ${AWS_SECRET_ACCESS_KEY}